# Meson cross file for building C/C++ deps (cairo) as wasm via Emscripten.
# Generated for the wotm project. EMSDK is at C:/en/emsdk.
[binaries]
c          = 'C:/en/emsdk/upstream/emscripten/emcc.exe'
cpp        = 'C:/en/emsdk/upstream/emscripten/em++.exe'
ar         = 'C:/en/emsdk/upstream/emscripten/emar.exe'
ranlib     = 'C:/en/emsdk/upstream/emscripten/emranlib.exe'
strip      = 'C:/en/emsdk/upstream/emscripten/emstrip.exe'
pkg-config = 'C:/Users/Daniel/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0/LocalCache/local-packages/Python313/site-packages/pkgconf/.bin/pkgconf.EXE'

[host_machine]
system     = 'emscripten'
cpu_family = 'wasm32'
cpu        = 'wasm32'
endian     = 'little'

[properties]
needs_exe_wrapper = true
